name: Build

on:
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*

      - name: Install dependencies
        run: npm clean-install

      - name: Build project
        run: npm run build
