name: Create a release on push to release branches

on:
  push:
    branches:
      - main
      - next
      - beta
      - "*.x"

permissions:
  contents: read

jobs:
  release:
    name: Generate a release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*

      - name: Install dependencies
        run: npm clean-install

      - name: Build project
        run: npm run build

      - name: Audit signatures
        run: npm run audit

      - name: Generate the release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
